---

linters:
  # Enable specific linters, in addition to those enabled by default:
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - funlen
    - gocognit
    - goconst
    - gocritic
    - goimports
    - revive
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - nestif
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - tparallel

linters-settings:
  dogsled:
    number-of-blank-identifiers: 3

issues:
  exclude-rules:
    - path: ".*_test.go"
      linters:
        - funlen

